[package]
name = "simploxide-client"
version = "0.1.0"
authors = ["a1akris <alkrivitskiy@pm.me>"]
edition = "2024"
license = "MIT OR Apache-2.0"

description = "SimpleX-Chat API client"
readme = "README.md"
repository = "https://github.com/a1akris/simploxide"
documentation = "https://docs.rs/simploxide-client"
categories = ["network-programming", "asynchronous", "web-programming::websocket"]
keywords = ["simplex", "chat", "websocket", "client"]

[features]
bon = ["simploxide-api-types/bon"]


[dependencies]
futures.workspace = true
serde_json.workspace = true
tokio-stream.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }

simploxide-core = { version = "0.1", path = "../simploxide-core"}
simploxide-api-types = { version = "0.1", path = "../simploxide-api-types" }
