/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn hs_init(argc: ::std::os::raw::c_int, argv: *mut *mut *mut ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn hs_init_with_rtsopts(
        argc: *mut ::std::os::raw::c_int,
        argv: *mut *mut *mut ::std::os::raw::c_char,
    );
}
pub type chat_ctrl = *mut ::std::os::raw::c_long;
unsafe extern "C" {
    pub fn chat_migrate_init(
        path: *const ::std::os::raw::c_char,
        key: *const ::std::os::raw::c_char,
        confirm: *const ::std::os::raw::c_char,
        ctrl: *mut chat_ctrl,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_close_store(ctrl: chat_ctrl) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_reopen_store(ctrl: chat_ctrl) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_send_cmd(
        ctrl: chat_ctrl,
        cmd: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_recv_msg_wait(
        ctrl: chat_ctrl,
        wait: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_parse_markdown(str_: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_parse_server(str_: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_password_hash(
        pwd: *const ::std::os::raw::c_char,
        salt: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_valid_name(name: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_json_length(str_: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn chat_encrypt_media(
        ctrl: chat_ctrl,
        key: *const ::std::os::raw::c_char,
        frame: *const ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_decrypt_media(
        key: *const ::std::os::raw::c_char,
        frame: *const ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_write_file(
        ctrl: chat_ctrl,
        path: *const ::std::os::raw::c_char,
        data: *const ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_read_file(
        path: *const ::std::os::raw::c_char,
        key: *const ::std::os::raw::c_char,
        nonce: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_encrypt_file(
        ctrl: chat_ctrl,
        fromPath: *const ::std::os::raw::c_char,
        toPath: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn chat_decrypt_file(
        fromPath: *const ::std::os::raw::c_char,
        key: *const ::std::os::raw::c_char,
        nonce: *const ::std::os::raw::c_char,
        toPath: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
